### ISSUE TITLE
quick questions

### ISSUE THREAD

**Issue by KnowsCount** [timofeji/cheapeth-faucet#1]
hi Timofej!

I am a newbie at this cryptocurrency stuff so I have two questions about your project. 

1. How do I know my `Address`?
2. How does this even work... Does cheapETH still cost money?

Also, I am to open up PRs enhancing the current website... especially adding an FAQ part for people like me.

**Comment by timofeji** [comment]
<img width="352" alt="Screen Shot 2021-02-28 at 5 13 33 PM" src="https://user-images.githubusercontent.com/11130291/109425453-968b0980-79e8-11eb-9aad-991f76b9119e.png">

1.)You get your address by going into metamask and clicking the account button, which copies ur address to the clipboard.

2.) CheapETH is just a fork of ethereum(like Binance smart chain). Test nets like Ropsten/Kovan have free eth, cheapETH is cheap not free, which means you can simulate market forces.

You make app, you test on cheapeth with market forces. you port to main net; you buy lambo. IS EZ.

Follow me on github; I do this for clout

**Comment by KnowsCount** [comment]
followed ya! issues closed.
